### ISSUE TITLE
Suggestion: output .LinkTitle in breadcrumb instead of .Title

### ISSUE THREAD

**Issue by ChristopheF** [hbstack/breadcrumb#204]
This is not really an issue, rather a suggestion
I believe it would make more sense to use .LinkTitle instead of .Title to output text in the breadcrumb (in both ancestor.html and index.html).
It would make the breacrumb content shorter (usually linktitle defines shorter titles in the front matter), and identical to the menu content, so that navigation would look more consistent.

You might prefer to implement a configuration setting to allow specifying which front matter entry to use for the breadcrumb.
Or not to change anything.

**Comment by razonyang** [comment]
Make sense.
